# f=open('n5.py','w')
# print("file creted")
# print(f.name)
# print(f.mode)
# print(f.readable())
# print(f.writable())
# print(f.closed)
# f.close()
# print(f.closed)


# f=open('x1.py','r')
# print("file creted")
# print(f.name)
# print(f.mode)
# print(f.readable())
# print(f.writable())
# print(f.closed)
# f.close()
# print(f.closed)

# f=open('n4.py','r')
# print("file created")
# print(f.name)
# print(f.mode)
# print(f.readable())
# print(f.writable())
# print(f.closed)
# f.close()
# print(f.closed)


# f=open('x1.py','a')
# print("file created")
# print(f.name)
# print(f.mode)
# print(f.readable())
# print(f.writable())
# print(f.closed)
# f.close()
# print(f.closed)
# print("Hello")

# f=open('x1.txt','w')
# print("file created")
# print(f.name)
# print(f.mode)
# print(f.readable())
# print(f.writable())
# print(f.closed)
# # data="This is file handelling class"
# data=['python\n','java\n','php\n']
# f.writelines(data)
# f.close()

# f=open('x1.txt')
# print(f.readable())
# data=f.read(5)
# data=f.read()
# data=f.readline()
# data=f.readlines()
# data=f.read(5)
# print(data)
# data2=f.read(7)
# print(data2)
# print(f.tell())
# f.close()

# cursor position tell()
# cursor movement seek()

f=open('x1.txt','r')
data=f.read(5)
print(data)
f.seek(0,0)
data2=f.read(6)
print(data2)


